# Matrices and Linear Algebra Fundamentals

## Vector and Real Co-ordinate Sapce

![images](./images/vector&space.png)

**Note**: `R^n` is the `n-dimensional` real co-ordinate space.

### Vector in Python

In [20]:
# Represent a vector in python 
# import numpy 
import numpy as np

v = np.array([1,2,3]) # Use NumPy to create a one-dimensional array.

print(v)

[1 2 3]


In [21]:
# Create 2 and 3 dimensional vector
two_dim = np.array([[1,2],[2,3],[3,4]])
print(two_dim)

three_dim = np.array([[[1,2,3],[3,4,5],[6,7,8]]])
print(three_dim)

[[1 2]
 [2 3]
 [3 4]]
[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


## Adding Vectors

![images](./images/vector-addition.png)

### Adding Vector in Python

In [22]:
a = np.array([6, -2])
b = np.array([-4, 4])

c = a + b # "+" operator perform vector addition in numpy python.
print(c)

d = b + a 
print(c)

assert (c.all() == d.all()) # check all the element of c and d are equal or not
# so we can say "a + b = b + a"

[2 2]
[2 2]


## Multiply a Vector By Scalar

![images](images/vector-scalar-multiplication.png)

### Vector Scalar Multiplication in Python

In [23]:
a = np.array([2,1])

b = 2 * a
print(b)

c = -1 * a
print(c)

d = -2 * a
print(d)

[4 2]
[-2 -1]
[-4 -2]


## Unit Vector

![images](./images/unit-vector.png)