### 1. Import the numpy package under the name `np`

In [1]:
import numpy as np

### 2. Print the numpy version and configuration

In [2]:
np.version.version

'1.19.5'

In [3]:
np.__version__

'1.19.5'

In [4]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


### 3. Create a `null` vector of size 10

In [5]:
null = np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [6]:
items = np.zeros((4,4))
items

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
print(f"Memory size of the array is = {items.size * items.itemsize} bytes.")

Memory size of the array is = 128 bytes.


### 5. How to get the documentation of the numpy add function from the command line?

In [8]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
       [ 0.]])

>

### 6. Create a null vector of size 10 but the fifth value which is 1

In [9]:
nums = np.zeros(10)
nums[4] = 1
nums

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
nums = np.arange(10) == 4
print(nums)
nums = nums * 1
print(nums)

[False False False False  True False False False False False]
[0 0 0 0 1 0 0 0 0 0]


### 7. Create a vector with values ranging from 10 to 49

In [11]:
nums = np.arange(10,50)
nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [12]:
nums = np.array([10,234,12,34, 10,23])
nums

array([ 10, 234,  12,  34,  10,  23])

In [13]:
nums = nums[::-1]
nums

array([ 23,  10,  34,  12, 234,  10])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
nums = np.arange(9).reshape(3,3)
nums

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [15]:
nums = np.array([1,2,0,0,4,0])
nums

array([1, 2, 0, 0, 4, 0])

In [16]:
nums.nonzero()

(array([0, 1, 4]),)

### 11. Create a 3x3 identity matrix

In [17]:
identity = np.identity(3)
identity.shape

(3, 3)

### 12. Create a 3x3x3 array with random values

In [18]:
nums = np.array(np.random.randint(1,100, 3*3*3)).reshape((3,3,3))
nums

array([[[99, 28, 70],
        [14,  8,  7],
        [42,  9, 38]],

       [[74, 40, 42],
        [ 7,  5, 11],
        [81, 90,  8]],

       [[11, 51, 46],
        [55, 78, 13],
        [74, 46, 32]]])

In [19]:
nums[0]

array([[99, 28, 70],
       [14,  8,  7],
       [42,  9, 38]])

In [20]:
nums[0][1]

array([14,  8,  7])

In [21]:
nums[0][1][2]

7

### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [22]:
nums = np.array(np.random.randint(1,200, 10*10)).reshape((10,10))
nums

array([[148,  88,  14,  51,  51, 168, 147, 132,  29,  68],
       [ 71, 127,  84,   5, 102,  59, 170,   7,  25, 180],
       [ 28,  78, 117, 126, 149,  24,  13,  51, 112,  71],
       [115,  36,  81,  99,  87, 171,  30,  81,   4, 145],
       [161, 105,  50, 181,  77,  36,  86,  81,  33,  14],
       [ 72, 133, 165,  96,  20, 127, 137,  16, 191,  15],
       [122,  68,  39,  50,  66, 101,  93, 174, 192,  17],
       [101, 132,  47, 163, 147, 150, 140, 174,  49, 153],
       [189, 186,  25,  89, 173, 193,  62,  26,  67, 100],
       [ 12,  23,  18, 104,  42, 161, 130,  95,  86, 125]])

In [23]:
np.max(nums)

193

In [24]:
np.min(nums)

4

### 14. Create a random vector of size 30 and find the mean value

In [25]:
nums = np.array(np.random.randint(1,20, 30))
nums

array([10,  9,  6, 17, 17,  8, 17, 19, 13, 15, 10,  3, 11,  8, 11, 16, 19,
       17, 17, 19, 16,  9,  9, 17, 18, 10, 14, 12, 16,  7])

In [26]:
nums = np.mean(nums)
nums

13.0

### 15. Create a 2d array with 1 on the border and 0 inside 

In [27]:
nums = np.ones((5,5))
nums

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
nums[1:-1,]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
nums[:,1:-1]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
nums[1:-1, 1:-1] = 0
nums

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 16. How to add a border (filled with 0's) around an existing array? 

In [31]:
nums = np.array(np.random.randint(1,10, 5*5)).reshape((5,5))
nums

array([[2, 3, 7, 6, 2],
       [9, 1, 1, 2, 3],
       [4, 7, 8, 4, 1],
       [4, 6, 6, 2, 7],
       [9, 6, 2, 2, 4]])

In [32]:
nums = np.pad(nums, pad_width=1, mode='constant', constant_values='0')
nums

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 2, 3, 7, 6, 2, 0],
       [0, 9, 1, 1, 2, 3, 0],
       [0, 4, 7, 8, 4, 1, 0],
       [0, 4, 6, 6, 2, 7, 0],
       [0, 9, 6, 2, 2, 4, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [33]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False
